name: s3 sync with filebase
on:
    workflow_dispatch: 
    schedule:
        - cron: '0 * * * *'
permissions:
    id-token: write
    contents: read

jobs:
    s3sync:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              id: aws-creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE }}
                aws-region: eu-west-3
                role-session-name: GH-SESSION
                output-credentials: true


            - name: Install Rclone
              run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
            
            - name: Git Checkout 
              uses: actions/checkout@v3
            
            - name: Using Jinja 2 Action
              uses: cuchi/jinja2-action@v1.2.2
              with:
                template: rclone.template.conf
                output_file: rclone.prod.conf
                strict: true
                variables: |
                  AWS_ACCESS_KEY_ID=${{ steps.aws-creds.outputs.aws-access-key-id }}
                  AWS_SECRET_ACCESS_KEY=${{ steps.aws-creds.outputs.aws-secret-access-key }}
                  FILEBASE_ACCESS_KEY_ID=${{ secrets.FILEBASE_ACCESS_KEY_ID }}
                  FILEBASE_SECRET_ACCESS_KEY=${{ secrets.FILEBASE_SECRET_KEY_ID }}
            - name: Showing File Content
              run: cat rclone.prod.conf