name: s3 sync with filebase
on:
    workflow_dispatch: 
    schedule:
        - cron: '0 * * * *'
permissions:
    id-token: write
    contents: read
    
jobs:
    s3sync:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "hello"
            - name: Install Rclone
              run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
            
            - name: Git Checkout 
              uses: actions/checkout@v3